osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - public/.components
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - graphicsmagick
      - libgnome-keyring-dev
      - icnsutils
      - xz-utils

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
  - nvm install 6.2
  - npm install electron-builder@5.12.1
  - npm install
  - npm install tournamenter
  - npm prune

script:
- npm run release

branches:
  only:
    - deploy
