version: 1.0.{build}

platform:
  - x64

cache:
  - node_modules
  - public\.components
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install electron-builder@5.12.1
  - npm install
  - npm install tournamenter
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off

branches:
  only:
    - deploy
